apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  selector:
    matchLabels:
      app: auth-svc
  template:
    metadata:
      name: auth-svc
      labels:
        app: auth-svc
    spec:
      containers:
        - name: auth
          image: myonim/auth
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY
  replicas: 1

---
apiVersion: v1
kind: Service
metadata:
  name: auth-svc
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: auth-svc
